<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="author" content="Elie NEHME" />
        <meta name="robots" content="all" />
        <?php
        $uri = $this->router->getUrlPath();
        ?>
        <link rel="canonical" href="https://test.com/<?php echo $uri ?>" title="herbatica lebanon"/>
    </head>
    <body>
        <div><?php echo $this->item ?></div>
        <div><?php echo $this->product ?></div>
    </body>
</html>